x

diff --git a/.scripts/gen-proto b/.scripts/gen-proto
--- a/.scripts/gen-proto
+++ b/.scripts/gen-proto
@@ -59,6 +59,20 @@ generate_proto_code() {
   
 }
 
+# ******************************************************************************
+#    HELPER FUNCS
+
+
+# check for required binaries
+check_required_binaries() {
+  local readonly bin_name="$1"
+
+  if [[ ! $(command -v ${bin_name}) ]]; then
+    log_error "Missing binary: '$bin_name' is required to run this script but is not in the system's PATH"
+    exit 1
+  fi
+}
+
 
 # ******************************************************************************
 #    LOGGERS
